export const WALLPAPER_STYLES = `
.dsh-wallpaper-page{display:flex;flex-direction:column;gap:20px;max-width:840px;color:var(--dsw-alias-label-primary);font-size:14px;line-height:22px}
.dsh-wallpaper-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.dsh-wallpaper-heading h2,.dsh-wallpaper-group h3{margin:0;font-weight:500}.dsh-wallpaper-heading h2{font-size:18px;line-height:26px}.dsh-wallpaper-group h3{font-size:15px;line-height:24px}.dsh-wallpaper-muted{margin:4px 0 0;color:var(--dsw-alias-label-tertiary);font-size:12px;line-height:18px}
.dsh-wallpaper-status{padding:8px 12px;border-radius:8px;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary)}.dsh-wallpaper-status[data-error=true]{color:var(--dsw-alias-state-error-primary)}
.dsh-wallpaper-source-grid{display:grid;grid-template-columns:minmax(220px,1fr) minmax(260px,1.3fr);gap:12px}.dsh-wallpaper-source{display:flex;flex-direction:column;gap:10px;padding:14px;border:1px solid var(--dsw-alias-border-l2);border-radius:12px}.dsh-wallpaper-source h3{margin:0;font-size:15px;line-height:24px;font-weight:500}.dsh-wallpaper-source-row{display:flex;gap:8px;align-items:flex-end}.dsh-wallpaper-source-row>*{min-width:0}.dsh-wallpaper-field{display:flex;flex-direction:column;gap:4px;flex:1;color:var(--dsw-alias-label-secondary);font-size:12px}.dsh-wallpaper-input,.dsh-wallpaper-select{box-sizing:border-box;width:100%;height:34px;padding:0 10px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);font:inherit}.dsh-wallpaper-color{width:44px;height:34px;padding:2px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent}
.dsh-wallpaper-button{box-sizing:border-box;display:inline-flex;align-items:center;justify-content:center;height:34px;padding:0 13px;border:1px solid var(--dsw-alias-border-l2);border-radius:17px;background:transparent;color:var(--dsw-alias-label-primary);font:inherit;cursor:pointer;white-space:nowrap}.dsh-wallpaper-button:hover:not(:disabled){background:var(--dsw-alias-interactive-bg-hover)}.dsh-wallpaper-button[data-primary=true]{border-color:transparent;background:var(--dsw-alias-button-primary-fill);color:var(--dsw-alias-label-primary-foreground)}.dsh-wallpaper-button[data-danger=true]{border-color:transparent;color:var(--dsw-alias-state-error-primary)}.dsh-wallpaper-button:disabled{opacity:.45;cursor:default}.dsh-wallpaper-button:focus-visible,.dsh-wallpaper-input:focus-visible,.dsh-wallpaper-select:focus-visible,.dsh-wallpaper-color:focus-visible{outline:none;box-shadow:0 0 0 2px var(--dsw-alias-brand-primary)}
.dsh-wallpaper-group{display:flex;flex-direction:column;gap:10px}.dsh-wallpaper-library{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:10px}.dsh-wallpaper-card{overflow:hidden;border:1px solid var(--dsw-alias-border-l2);border-radius:12px;background:var(--dsw-alias-bg-layer-1)}.dsh-wallpaper-card[data-active=true]{border-color:var(--dsw-alias-brand-primary)}.dsh-wallpaper-preview{display:block;width:100%;aspect-ratio:16/9;object-fit:cover;background:var(--dsw-alias-bg-layer-2)}.dsh-wallpaper-preview-paused{display:grid;place-items:center;color:var(--dsw-alias-label-tertiary);font-size:12px}.dsh-wallpaper-card-body{display:flex;flex-direction:column;gap:8px;padding:10px}.dsh-wallpaper-card-title{display:flex;justify-content:space-between;gap:8px}.dsh-wallpaper-card-title strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-weight:500}.dsh-wallpaper-badge{flex:none;color:var(--dsw-alias-label-tertiary);font-size:11px}.dsh-wallpaper-card-actions{display:flex;justify-content:space-between;gap:6px}.dsh-wallpaper-card-actions .dsh-wallpaper-button{height:28px;padding:0 10px;font-size:12px}
.dsh-wallpaper-controls{display:grid;grid-template-columns:repeat(2,minmax(220px,1fr));gap:12px 18px;padding:14px;border-radius:12px;background:var(--dsw-alias-bg-module-platform)}.dsh-wallpaper-range{display:grid;grid-template-columns:96px minmax(100px,1fr) 48px;align-items:center;gap:8px}.dsh-wallpaper-range output{text-align:right;color:var(--dsw-alias-label-tertiary);font-variant-numeric:tabular-nums}.dsh-wallpaper-switch{display:flex;align-items:center;gap:8px;min-height:34px}.dsh-wallpaper-empty{padding:24px;border:1px dashed var(--dsw-alias-border-l2);border-radius:12px;text-align:center;color:var(--dsw-alias-label-tertiary)}
@media(max-width:720px){.dsh-wallpaper-source-grid,.dsh-wallpaper-controls{grid-template-columns:1fr}.dsh-wallpaper-source-row{align-items:stretch;flex-direction:column}.dsh-wallpaper-source-row .dsh-wallpaper-button{align-self:flex-start}.dsh-wallpaper-range{grid-template-columns:84px minmax(80px,1fr) 44px}}
@media(prefers-reduced-motion:reduce){.dsh-wallpaper-page *{scroll-behavior:auto!important;transition:none!important}}
`

export function installWallpaperStyles(doc: Document): () => void {
  const style = doc.createElement('style')
  style.dataset.dshWallpaperStyles = 'true'
  style.textContent = WALLPAPER_STYLES
  doc.head.append(style)
  return () => { style.remove() }
}
